---
- name: Write the config file for the controller-manager
  template: src=controller-manager.j2 dest={{ kube_config_dir }}/controller-manager
  notify:
    - restart controller-manager

#- name: Write the kubecfg (auth) file for controller-manager
#  template: src=controller-manager.kubeconfig.j2 dest={{ kube_config_dir }}/controller-manager.kubeconfig

- name: Enable controller-manager
  service:
    name: kube-controller-manager
    enabled: yes
    state: started