---
- name: CentOS | Install kubernetes node
  yum:
    pkg=kubernetes-node
    state=latest

- name: Create kubernetes log directory
  file:
    path: "{{ item }}"
    state: directory
    owner: kube
    group: kube
  with_items:
    - "{{ kube_log_dir }}"
    - "{{ kube_log_proxy }}"
    - "{{ kube_log_kubelet }}"
    
- include: kubelet.yml
- include: proxy.yml
- include: post.yml