---
- name: install flannel
  yum: name=flannel state=present

- name: set flannel config file
  template:
    src: flanneld.j2
    dest: /etc/sysconfig/flanneld

- name: Create flannel config file to go in etcd
  template: src=flannel-config.json.j2 dest=/tmp/flannel-conf.json
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Load the flannel config file into etcd
  shell: etcdctl set "/{{ cluster_name }}/network/config" < /tmp/flannel-conf.json
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: enable and start flannel
  service:
    name: flanneld
    enabled: yes
    state: started
