---
etcd_version: 2.2.3

etcd_client_port: 2379
etcd_peer_port: 2380
etcd_peers_group: etcd

etcd_url_scheme: http
etcd_peer_url_scheme: http
# Set correspondingly to true when use https values above to enable cert auth
etcd_client_cert_auth: false
etcd_peer_client_cert_auth: false

etcd_cert_group: root

etcd_data_dir: /var/lib/etcd

etcd_conf_dir: /etc/etcd

etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-k8-cluster

# Interface on which etcd listens.
# It is useful when you want define common network interface for etcd clusters and the interface is not connected to other machines (i.e. use same network interface for setup a etcd clusters),
# for example as in Vagrant+VirtualBox configuration.
# Note that this variable can't be set in per-host manner with current implementation.
# If not specified, fact "ansible_default_ipv4.address" will be applied by every host itself.
etcd_interface: ""

etcd_machine_address: "{% if etcd_interface != '' %}{{ hostvars[inventory_hostname]['ansible_' + etcd_interface].ipv4.address }}{%- else %}{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}{% endif %}"
etcd_initial_advertise_peer_urls: "{{ etcd_peer_url_scheme }}://{{ etcd_machine_address }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "{{ etcd_peer_url_scheme }}://0.0.0.0:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "{{ etcd_url_scheme }}://{{ etcd_machine_address }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "{{ etcd_url_scheme }}://0.0.0.0:{{ etcd_client_port }}"

etcd_enable: true
